---
name: Build

on:
  pull_request_target:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Find JIRA title
        id: find_ticket_id
        continue-on-error: true
        uses: MeilCli/regex-match@v1
        with:
          search_string: ${{ github.event.pull_request.title }}
          regex_pattern: 'JIRA-\d+'
          regex_option: 'i'
      
      - name: Check output
        run: |
            echo ${{ steps.find_ticket_id.outputs.matched_first }}
            echo The above should be the reference to a JIRA ticket that begins JIRA- and ends with a number